import type { Metadata } from "next";
import { Arima } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

const arimaSans = Arima({
  variable: "--font-arima-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${arimaSans.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
