import type { Metadata } from "next";
import { Arima } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

const arimaSans = Arima({
  variable: "--font-arima-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Open Source Hive",
  description: "Generated by TheGym Rwanda",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${arimaSans.variable} antialiased`}>
        <Navbar />
        <div className="container">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
